"""init schema

Revision ID: 2d34ede14bae
Revises:
Create Date: 2026-08-19 13:55:02.870275

"""

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2d34ede14bae"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # pgvector must exist before any HALFVEC column/index below is created.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "role", postgresql.ENUM("student", "alumni", "admin", name="user_role"), nullable=False
        ),
        sa.Column("full_name", sa.String(length=255), nullable=True),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("zalo_id", sa.String(length=100), nullable=True),
        sa.Column("active_points", sa.Integer(), server_default="0", nullable=False),
        sa.Column("hashed_password", sa.String(length=1024), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("phone"),
        sa.UniqueConstraint("zalo_id"),
    )
    op.create_table(
        "alumni_profiles",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("raw_text", sa.Text(), nullable=True),
        sa.Column("embedding", pgvector.sqlalchemy.halfvec.HALFVEC(dim=1536), nullable=True),
        sa.Column("skills", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("current_job", sa.String(length=255), nullable=True),
        sa.Column("company", sa.String(length=255), nullable=True),
        sa.Column("courses_taken", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_index(
        "ix_alumni_profiles_embedding_hnsw",
        "alumni_profiles",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding": "halfvec_cosine_ops"},
    )
    op.create_table(
        "mentorship_sessions",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("student_id", sa.UUID(), nullable=False),
        sa.Column("alumni_identifier", sa.String(length=255), nullable=False),
        sa.Column("brief", sa.Text(), nullable=True),
        sa.Column(
            "channel",
            postgresql.ENUM("meet", "zalo_chat", "text_reply", name="session_channel"),
            nullable=True,
        ),
        sa.Column("meet_link", sa.Text(), nullable=True),
        sa.Column(
            "status",
            postgresql.ENUM("PENDING", "ACCEPTED", "DONE", "DECLINED", name="session_status"),
            server_default="PENDING",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["student_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_sessions_alumni_identifier", "mentorship_sessions", ["alumni_identifier"], unique=False
    )
    op.create_table(
        "pending_points",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("identifier", sa.String(length=255), nullable=False),
        sa.Column("points", sa.Integer(), server_default="10", nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=True),
        sa.Column(
            "status",
            postgresql.ENUM("PENDING", "CLAIMED", "EXPIRED", name="pending_points_status"),
            server_default="PENDING",
            nullable=False,
        ),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["session_id"], ["mentorship_sessions.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_pending_identifier", "pending_points", ["identifier"], unique=False)
    op.create_index(
        "idx_pending_identifier_status", "pending_points", ["identifier", "status"], unique=False
    )
    op.create_table(
        "proxy_messages",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column(
            "sender_role",
            postgresql.ENUM("student", "alumni", name="proxy_message_sender_role"),
            nullable=False,
        ),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["session_id"], ["mentorship_sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_proxy_messages_session_id", "proxy_messages", ["session_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_proxy_messages_session_id", table_name="proxy_messages")
    op.drop_table("proxy_messages")
    op.drop_index("idx_pending_identifier_status", table_name="pending_points")
    op.drop_index("idx_pending_identifier", table_name="pending_points")
    op.drop_table("pending_points")
    op.drop_index("idx_sessions_alumni_identifier", table_name="mentorship_sessions")
    op.drop_table("mentorship_sessions")
    op.drop_index(
        "ix_alumni_profiles_embedding_hnsw",
        table_name="alumni_profiles",
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding": "halfvec_cosine_ops"},
    )
    op.drop_table("alumni_profiles")
    op.drop_table("users")
    # ### end Alembic commands ###

    # Drop the enum types SQLAlchemy created implicitly for the ENUM columns
    # above — op.drop_table() does not remove them on its own.
    for enum_name in (
        "proxy_message_sender_role",
        "pending_points_status",
        "session_status",
        "session_channel",
        "user_role",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")

    op.execute("DROP EXTENSION IF EXISTS vector")
